### ISSUE TITLE
Problem with installation of GoReleaser

### ISSUE THREAD

**Issue by Cl00e9ment** [sazap10/ovh-ip-updater-go#15]
When I built ovh-ip-updater-go for ARM64, I had to remove the `-s v1.21.0` option from this line:

```dockerfile
RUN curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.21.0
```

Indeed, this option was responsible of the script exiting with code 1.
Is this option useful? Because it isn't present on [the official page of GoReleaser](https://goreleaser.com/).

Here is the logs:
```
Step 11/22 : RUN curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.21.0
 ---> Running in 15b439c85b44
golangci/golangci-lint info checking GitHub for tag 'v1.21.0'
golangci/golangci-lint info found version: 1.21.0 for v1.21.0/linux/arm64
ERROR: Service 'ovh-ip-updater-go' failed to build: The command '/bin/sh -c curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.21.0' returned a non-zero code: 1
```

Also, it would be great if ovh-ip-updater-go was available on Docker Hub for ARM64.

**Comment by sazap10** [comment]
> When I built ovh-ip-updater-go for ARM64, I had to remove the `-s v1.21.0` option from this line:
> 
> ```dockerfile
> RUN curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.21.0
> ```
> 
> Indeed, this option was responsible of the script exiting with code 1.
> Is this option useful? Because it isn't present on [the official page of GoReleaser](https://goreleaser.com/).
This was complaining about https://github.com/golangci/golangci-lint rather than GoReleaser. I have updated the version and it should now work. I have also manually pushed an ARM64 image to the latest tag, I plan to add this to my CI soon. Let me know if that works for you.

**Comment by Cl00e9ment** [comment]
It works perfectly.
Thank you a lot.
